### Datasource info
spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/h2-data/h2-data-backup;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
  #  password: password
  #  url: jdbc:mysql://localhost:3306/myretail_users?servetTimezone=UTC
  #  username: root
  #  password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/database/liquibase/change-logs/changelog-master.xml
  h2:
    console:
      enabled: true