### Datasource info
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myretail_users?servetTimezone=UTC
    username: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true